import { StyleSheet } from "react-native";
import { COLORS } from "./colors";

export const styles = StyleSheet.create({
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: COLORS.card,
      borderBottomColor: COLORS.line,
      borderBottomWidth: 1,
    },
    logo: { width: 38, height: 38, marginRight: 10, tintColor: '#fff' },
    brand: {
      color: COLORS.text,
      fontWeight: '900',
      fontSize: 18,
      letterSpacing: 0.3,
    },
    subtitle: { color: COLORS.muted, fontSize: 12 },
    cartBtn: {
      backgroundColor: COLORS.brand,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
    },
    badge: {
      position: 'absolute',
      top: -8,
      right: -8,
      backgroundColor: '#ffd54a',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 10,
    },
  
    tabbar: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      flexDirection: 'row',
      backgroundColor: COLORS.card,
      borderTopColor: COLORS.line,
      borderTopWidth: 1,
    },
    tabItem: { flex: 1, alignItems: 'center', paddingVertical: 10 },
    tabTxt: { color: COLORS.muted, fontWeight: '700' },
    tabIndicator: {
      width: 28,
      height: 3,
      backgroundColor: COLORS.brand,
      borderRadius: 2,
      marginTop: 6,
    },
  
    input: {
      backgroundColor: '#0b0b0d',
      borderRadius: 14,
      width: 350,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 20,
      color: COLORS.text,
      borderWidth: 5,
      borderColor: COLORS.line,
      marginTop: 15, marginBottom: 15,
    },

    label: {
      color: COLORS.text,   // branco
      fontWeight: '700',
      fontSize: 14,
      marginBottom: 6,
    },
  
    inputSenha: {
      backgroundColor: '#0b0b0d',
      borderRadius: 14,
      width: 350,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 20,
      color: COLORS.text,
      borderWidth: 5,
      borderColor: COLORS.line,
      marginBottom: 30,
    },
  
    banner: {
      margin: 16,
      backgroundColor: COLORS.card,
      borderRadius: 20,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderWidth: 1,
      borderColor: COLORS.line,
    },
    bannerTitle: { color: COLORS.text, fontSize: 18, fontWeight: '800' },
    bannerSub: { color: COLORS.muted, marginTop: 4 },
    bannerLogo: { width: 72, height: 72, tintColor: '#fff' },
  
    search: {
      marginHorizontal: 16,
      backgroundColor: '#0b0b0d',
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      color: COLORS.text,
      borderWidth: 1,
      borderColor: COLORS.line,
    },
  
    sectionTitle: {
      color: COLORS.text,
      fontWeight: '800',
      fontSize: 16,
      paddingHorizontal: 16,
      marginTop: 16,
      marginBottom: 8,
    },
  
    chip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      backgroundColor: '#1a1a1d',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: COLORS.line,
    },
    chipTxt: { color: COLORS.text, fontWeight: '700' },
  
    card: {
      marginHorizontal: 16,
      marginVertical: 6,
      backgroundColor: COLORS.card,
      borderRadius: 18,
      padding: 10,
      flexDirection: 'row',
      gap: 10,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: COLORS.line,
    },
    cardImg: { width: 72, height: 72, borderRadius: 14, backgroundColor: '#000' },
    cardTitle: { color: COLORS.text, fontWeight: '700' },
    cardPrice: { color: '#ffd79a', marginTop: 4, fontWeight: '800' },
    addBtn: {
      backgroundColor: COLORS.brand,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
    },
  
    modalHeader: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderBottomColor: COLORS.line,
      backgroundColor: COLORS.card,
    },
    modalTitle: { color: COLORS.text, fontWeight: '800', fontSize: 16 },
    cartItem: {
      backgroundColor: '#0f0f12',
      borderRadius: 14,
      padding: 12,
      borderWidth: 1,
      borderColor: COLORS.line,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 12,
    },
    qtyRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    qtyBtn: {
      backgroundColor: '#fff',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
    },
  
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
    },
    sheet: {
      width: '100%',
      maxWidth: 520,
      backgroundColor: COLORS.card,
      borderRadius: 20,
      padding: 16,
      borderWidth: 1,
      borderColor: COLORS.line,
    },
    payBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      backgroundColor: '#1a1a1d',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: COLORS.line,
    },
    payTxt: { color: COLORS.text, fontWeight: '700' },
  
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 6,
    },
  
    orderCard: {
      marginHorizontal: 16,
      marginVertical: 8,
      backgroundColor: COLORS.card,
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
      borderColor: COLORS.line,
    },
  
    dot: { width: 12, height: 12, borderRadius: 6 },
  
    formCard: {
      margin: 16,
      backgroundColor: COLORS.card,
      borderRadius: 18,
      padding: 16,
      borderWidth: 1,
      borderColor: COLORS.line,
      gap: 8,
    },
  
    primaryBtn: {
      backgroundColor: COLORS.brand,
      width: 350,
      paddingVertical: 8,
      paddingHorizontal: 20,
      borderRadius: 50,
      alignItems: 'center',
      justifyContent: 'center',
    },
  
    btn_Logins: {
      width: 350,
      paddingVertical: 8,
      paddingHorizontal: 20,
      borderRadius: 50,
      alignItems: 'center',
      justifyContent: 'center',
    },
  
    textWhite: { 
      color: '#white', 
      fontWeight: '800'
     },
  
    primaryTxt: { color: '#000', fontWeight: '900', fontSize: 20},
    secondaryBtn: {
      backgroundColor: '#1a1a1d',
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 14,
      alignItems: 'center',
    },
  
    btnGoogleLogin: {
      width: 350,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#fff",
      borderRadius: 50,
      paddingVertical: 10,
      paddingHorizontal: 20,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowOffset: { width: 0, height: 2 },
      marginTop: 20,
      shadowRadius: 2,
      elevation: 2,
    },
  
    secondaryTxt: { color: COLORS.text, fontWeight: '800' },
    divider: { height: 1, backgroundColor: COLORS.line, marginVertical: 8 },

    // --- ADICIONAIS PARA O CARRINHO ---
    itemImage: {
      width: 55,
      height: 55,
      borderRadius: 10,
      marginRight: 10,
      backgroundColor: '#000',
    },
    itemInfo: {
      flex: 1,
    },
    itemTitle: {
      color: COLORS.text,
      fontSize: 14,
      fontWeight: '600',
    },
    itemSubtitle: {
      color: COLORS.muted,
      fontSize: 12,
      marginTop: 2,
    },
    quantityContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#2a2a2a",
      borderRadius: 10,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    quantityButton: {
      color: COLORS.brand,
      fontSize: 20,
      paddingHorizontal: 6,
    },
    quantityText: {
      color: COLORS.text,
      fontSize: 16,
      marginHorizontal: 6,
    },
    summary: {
      padding: 16,
      borderTopWidth: 1,
      borderColor: COLORS.line,
    },
    totalLabel: {
      color: COLORS.text,
      fontSize: 16,
      fontWeight: "700",
    },
    totalValue: {
      color: COLORS.brand,
      fontSize: 16,
      fontWeight: "700",
    },
    deliveryInfo: {
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    deliveryText: {
      color: COLORS.text,
      fontSize: 14,
      fontWeight: "600",
    },
    deliverySub: {
      color: COLORS.muted,
      fontSize: 12,
    },
    checkoutButton: {
      backgroundColor: COLORS.brand,
      paddingVertical: 16,
      borderRadius: 30,
      alignItems: "center",
      marginHorizontal: 16,
      marginTop: 10,
    },
    checkoutText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "700",
    },
});
